### ISSUE TITLE
Compile is always true in Gridsome

### ISSUE THREAD

**Issue by kgnfth** [windicss/windicss-webpack-plugin#10]
this is my gridsome.config.js file

```js
module.exports = {
  siteName: 'Gridsome',
  configureWebpack: (config) => {
    config.module.rules.push({
      test: /\.vue$/,
      use: [
        {
          loader: 'vue-windicss-preprocess',
          options: {
            config: 'tailwind.config.js', // tailwind config file path OR config object (optional)
            compile: false, // false: interpretation mode; true: compilation mode
            globalPreflight: true, // set preflight style is global or scoped
            globalUtility: true, // set utility style is global or scoped
            prefix: 'change-', // set compilation mode style prefix
          },
        },
      ],
    })
  },
  plugins: [
    {
      use: '@gridsome/source-strapi',
      options: {
        apiURL: `${process.env.API_URL || 'http://localhost:1337'}`,
        queryLimit: 1000, // Defaults to 100
        contentTypes: [`albums`],
      },
    },
  ],
}
```

i set compile to false but it still runs with `Compilation Mode`
i changed the prefix to `change-` to see if it reads my config but the result is still `windi-`

**Comment by harlan-zw** [comment]
> i tried it like this
> 
> ```js
> const WebpackWindiCSSPlugin = require('windicss-webpack-plugin').default
> 
> module.exports = {
>   siteName: 'Gridsome',
>   configureWebpack: {
>     plugins: [
>       new WebpackWindiCSSPlugin({
>         scan: {
>           dirs: ['./src'],
>           exclude: ['node_modules', '.git'],
>         },
>       }),
>     ],
>   }
> }
> ```
> 
> but it wont work

Hey @kgnfth. I haven't tried this with Gridsome yet but will take a look

**Comment by harlan-zw** [comment]
Official gridsome plugin has been added, see: https://github.com/windicss/gridsome-plugin-windicss

**Comment by kgnfth** [comment]
> Official gridsome plugin has been added, see: https://github.com/windicss/gridsome-plugin-windicss

Thank you very much bro
