### ISSUE TITLE
vue sfc custom block error

### ISSUE THREAD

**Issue by imshenshen** [windicss/windicss-webpack-plugin#103]
https://github.com/windicss/windicss-webpack-plugin/pull/102
after update 1.5.8 ，the [vue-i18n-loader](https://github.com/intlify/vue-i18n-loader) custom block `<i18n>` dose not work。the vue-i18n-loader didn't run any code

**Comment by harlan-zw** [comment]
Hey @imshenshen 

Thanks for reporting that issue. I've dug into the logic for pitching and found some underlying logic issues. There's a fix in 1.6.0 which should hopefully solve this and the issue in #102. 

Can you give it a go and let me know. @winixt Can you also test when you get a chance

I had some issues trying to get the <i18n> block working altogether in the vue2 vue-cli example app, as far as I could tell it wasn't related to windi, so if there's still a bug would you mind sharing a reproduction repo

**Comment by winixt** [comment]
I have written a custom loader to handle.
