### ISSUE TITLE
@layer The command does not work

### ISSUE THREAD

**Issue by viarotel** [windicss/windicss-webpack-plugin#104]
**Describe the bug**
@layer The command does not work
**Screenshots**
![image](https://user-images.githubusercontent.com/38282758/146483382-19bf02d2-9e9b-4a53-9a9e-57f16bc07415.png)
![image](https://user-images.githubusercontent.com/38282758/146483419-32b77038-51c9-40f6-857f-cfe45d56ed2d.png)

**Comment by harlan-zw** [comment]
Had some issues setting up tests with postcss, but if you put that code in a simple CSS file it seems to work correctly. See https://github.com/windicss/windicss-webpack-plugin/commit/baea54021e1726013b0b592c227ca7cd99f29c43

It might of been the windi update that fixed it, or just an issue with SFC & postcss
