### ISSUE TITLE
Error when use extractors on windi config

### ISSUE THREAD

**Issue by karyanayandi** [windicss/windicss-webpack-plugin#109]
**Describe the bug**
I use storybook with windicss webpack plugin and use extractors option like on documentation but there's error like below.
![Cheese_22 04 12_07 21 21](https://user-images.githubusercontent.com/25613501/162854120-0a2ddf56-bb9e-4f2c-bc09-068a4ad4789c.png)

### this is my windicss config

```
export default defineConfig({
  extract: {
    include: [
      "./packages/**/**/**/*{.js,.jsx,.ts,.tsx}",
      "./packages/**/**/**/**/*{.js,.jsx,.ts,.tsx}",
    ],
    extractors: [
      {
        extractor: (content) => {
          return { classes: content.match(/(?<=class:)[!@\w-]+/g) ?? [] }
        },
        extensions: ["tsx"],
      },
    ],
  },
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: colors.teal,
        secondary: colors.zinc,
      },
    },
  },
  plugins: [require("windicss/plugin/forms")],
})
```

**Comment by await-ovo** [comment]
@harlan-zw Hi, I can reproduce this issue on my side too, I think we might need to make the `@windicss/plugin-utils` compatible with custom extractor which return undefined tags, attributes values, etc.

The[ relevant code](https://github.com/windicss/vite-plugin-windicss/blob/main/packages/plugin-utils/src/extractors/helper.ts#L43) changed to this should work, and if it does, I'm happy to mention a PR: 

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/41503212/162877412-4342c868-dbc2-4ad1-b661-6d2fab843c57.png">


@karyanayandi A temporary solution here can be configured like this:

```js
export default defineConfig({
  extract: {
    include: [
      "./packages/**/**/**/*{.js,.jsx,.ts,.tsx}",
      "./packages/**/**/**/**/*{.js,.jsx,.ts,.tsx}",
    ],
    extractors: [
      {
        extractor: (content) => {
          return { 
             classes: content.match(/(?<=class:)[!@\w-]+/g) ?? [],
             attributes: {
               names: [],
               values: [],
             },
             tags: [],
             ids: []
          }
        },
        extensions: ["tsx"],
      },
    ],
  },
})
```
