### ISSUE TITLE
Removing the rule will cause other loaders to not get the correct options

### ISSUE THREAD

**Issue by keuby** [windicss/windicss-webpack-plugin#111]
**Describe the bug**
The loader removal operation was performed in the windicss-style-pitcher of the plug-in, which would cause other loaders to fail to get the loader options value configured in module.rules correctly, resulting in abnormal packing

**To Reproduce**
1. Clone repository 'https://github.com/keuby/unplugin-bug-demo'
2. Run 'yarn install && yarn build'
3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/32365592/164168946-c5ed9d61-f7e4-4515-90cf-33def998d0e1.png)

**Comment by harlan-zw** [comment]
Hey @keuby 

Thanks for digging into this and the reproduction repo, I was able to replicate the issue and find the problem. As far as I can tell [my solution](https://github.com/windicss/windicss-webpack-plugin/commit/f25545ac78e1539148921f087821e58b776cf125) fixes the issue without introducing any regression, but if you see anything obvious please let me know.

 The bug fix is in the new release 1.7.1
