### ISSUE TITLE
Optional chaining (?.) in dist/plugin.cjs makes build project crash while in Node.js version lower than 14

### ISSUE THREAD

**Issue by xliez** [windicss/windicss-webpack-plugin#112]
**Describe the bug**
Optional chaining (?.) in dist/plugin.cjs make build crash while in Node.js version lower than 14

**To Reproduce**
1. Clone repository '...'
2. Run '....'
3. See error

**Expected behavior**
Build pass

**Screenshots**
![image](https://user-images.githubusercontent.com/15049079/164180871-f2c72dca-ff22-4573-a629-b3c8a6eecea1.png)

**Additional context**

**Comment by harlan-zw** [comment]
Hey @xliez 

Thanks for reporting the issue! Have updated the build configuration for an es2019 target which should fix this.

If you have issues with 1.7.2 can you please let me know :)
