### ISSUE TITLE
why example run has error?

### ISSUE THREAD

**Issue by jetBn** [windicss/windicss-webpack-plugin#113]
![image](https://user-images.githubusercontent.com/26957220/166857565-30e1533c-723e-4844-9b30-91f5dc68f714.png)

**Comment by await-ovo** [comment]
`example/next`  use local `windicss-webpack-plugin`, maybe we should run `pnpm i` at the root of the repository, then build it, then run  dev in `exmaple/next` and we shouldn't run into this error~

**Comment by harlan-zw** [comment]
Thanks @await-ovo, that's right.

The proper workflow to use the example would be:
- `pnpm i`
- `pnpm build`
- cd `examples/next` 
- `yarn install` 
- `yarn dev`

The use of different package managers is a bit hacky but it was my solution to avoid hoisting issues with frameworks having different majors

**Comment by harlan-zw** [comment]
Actually, I think this was an issue introduced with https://github.com/windicss/windicss-webpack-plugin/pull/110 where the client isn't package

**Comment by harlan-zw** [comment]
Fixed in 1.7.3
