### ISSUE TITLE
Not compatible with Vue CLI 5 (Webpack 5)

### ISSUE THREAD

**Issue by cloydlau** [windicss/windicss-webpack-plugin#12]
Reproduce:
Head for `./example/vue2/package.json` and change all versions of vue-cli tools to `5.0.0-alpha.8` (latest).
Run `npm run build`, an error occurred: 
`Syntax Error: Thread Loader (Worker 0)
Cannot read property '$windyCSSService' of undefined`

**Comment by harlan-zw** [comment]
Hi @cloydlau 

This has been fixed in #13. I've also added a new example for vue-cli-5 here: https://github.com/windicss/windicss-webpack-plugin/tree/master/example/vue-cli-next

Note that the eslint dependency had to be removed.

Let me know if you have any further issues.

**Comment by cloydlau** [comment]
Hello, I've tried that vue-cli-5 example and I wonder if you are using `pnpm`, the situation is `pnpm` is ok but `yarn` don't, same error occurred when using `yarn`.

**Comment by harlan-zw** [comment]
> Hello, still the same error after I upgraded to `0.3.0`, very sweet for the vue-cli-5 example by the way.

Can you double-check it updated correctly? Seems weird it would have the same issue even after an upgrade.

Otherwise can you provide a reproduction repo and I can take a look?

**Comment by cloydlau** [comment]
https://github.com/cloydlau/reproduce.git

run `yarn && yarn build`

**Comment by harlan-zw** [comment]
Ah thanks @cloydlau, I was only doing `yarn dev`. Can reproduce this now

**Comment by harlan-zw** [comment]
Hey @cloydlau should be sorted in 0.3.1, can you please try and let me know how it goes.

There is also an official vue-cli plugin which should be working with this fix https://github.com/windicss/vue-cli-plugin-windicss

**Comment by cloydlau** [comment]
Doing ok in `0.3.2`, thanks.
