### ISSUE TITLE
how to use it in umijs?

### ISSUE THREAD

**Issue by LanJamRom** [windicss/windicss-webpack-plugin#63]

**Comment by harlan-zw** [comment]
Hey @LanJamRom 

I've added an umijs example, seems to work correctly as far as I could tell.

See: https://github.com/windicss/windicss-webpack-plugin/blob/master/example/umijs/.umirc.ts

Note you should replace 

`import WindiCSSWebpackPlugin from '../../dist/index.js'`

 with 

`import WebpackWindiCSSPlugin from 'windicss-webpack-plugin'`

Let me know if you have any issues

**Comment by LanJamRom** [comment]
Thanks a million！
