### ISSUE TITLE
Next.js example doesn't work

### ISSUE THREAD

**Issue by steakscience** [windicss/windicss-webpack-plugin#65]
Hi there,

The Next.js example doesn't seem to work. I've tried fixing the const require to not error, but even then it will not work.

Any help here would be appreciated, it seems like windi.css is not being imported?

**Comment by harlan-zw** [comment]
Hey @steakscience 

Firstly can you upgrade to v0.4.0. If this version doesn't work can you share your code with me?

As far as I can test locally the next example does work, however, the hot module reloading can sometimes be finicky, which is something I will look into separately. 

Your config should look something like this

```
const WindiCSSWebpackPlugin = require('windicss-webpack-plugin').default

module.exports = {
  webpack: config => {
    config.plugins.push(new WindiCSSWebpackPlugin({
      scan: {
        dirs: ['./'],
        exclude: ['node_modules', '.git', '.next/**/*'],
      },
    }))
    return config
  },
}
```

**Comment by steakscience** [comment]
Hi @harlan-zw,

It works perfectly now! Thank you 🤗
