### ISSUE TITLE
Importing external css breaks the build

### ISSUE THREAD

**Issue by razbakov** [windicss/windicss-webpack-plugin#71]
Importing css from `videojs` breaks build

### Steps to reproduce

```js
import videojs from "video.js";
import "video.js/dist/video-js.css";
```

### Actual result

```
ERROR  in ./node_modules/video.js/dist/video-js.css 

Syntax Error: SyntaxError                                                

(1:1) Unclosed block

> 1 | @font-face {
    | ^
  2 |   font-family: VideoJS;
  3 |   src: url(data:application/font-woff;

 @ ./node_modules/video.js/dist/video-js.css
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/windicss-webpack-plugin/dist/loaders/transform-template.js!./components/TVideoPlayer.vue?vue&type=script&lang=js&
```

It seems that windicss is trying to process imported css.

That's a huge drawback as it stops you from using almost any existing component, which requires css.

Might be related to windicss/windicss#102 and windicss/windicss#199

**Comment by harlan-zw** [comment]
Hey @razbakov

I've moved this issue into the webpack plugin project. 

Can you upgrade your package to v0.5.0 and try again. Alternatively, make sure you're excluding the node_modules folder from scanning, see: https://github.com/windicss/vite-plugin-windicss#scanning

**Comment by razbakov** [comment]
@harlan-zw thank you! it's working now! Tested with

```
"nuxt-vite": "^0.1.1",
"nuxt-windicss": "^1.2.2"
```
