### ISSUE TITLE
h-[calc(100% - 2rem)] don't work in umijs

### ISSUE THREAD

**Issue by LanJamRom** [windicss/windicss-webpack-plugin#77]
"windicss": "3.0.12",
"windicss-webpack-plugin": "0.6.1"

![image](https://user-images.githubusercontent.com/41603622/119599453-9c419100-be17-11eb-807a-425064610b93.png)
![image](https://user-images.githubusercontent.com/41603622/119599504-b54a4200-be17-11eb-9dd8-c99906624579.png)

**Comment by LanJamRom** [comment]
sorry

**Comment by transtone** [comment]
`h-[calc(100%-2rem)]` will work.
