### ISSUE TITLE
windicss-webpack-plugin + storybook, how to use?

### ISSUE THREAD

**Issue by Fl0pZz** [windicss/windicss-webpack-plugin#79]
hi, how can I friend storybook with windicss-webpack-plugin?

**Comment by harlan-zw** [comment]
Hey @Fl0pZz 

I have added some details in the docs for integration here: https://windicss.org/integrations/webpack.html#storybook, you can also check out the example repo I made https://github.com/windicss/windicss-webpack-plugin/tree/master/example/vue3-storybook
