### ISSUE TITLE
Build Next example failed

### ISSUE THREAD

**Issue by ModyQyW** [windicss/windicss-webpack-plugin#85]
**Describe the bug**

I got an error when I try to build Next example.

**To Reproduce**

1. Clone `windicss-webpack-plugin` repository
2. Run `yarn && yarn build` in the root
3. Go into `windicss-webpack-plugin/example/next` and run `yarn`
4. Update `next.config.js` (add `eslint` field)

```js
// const WindiCSS = require('windicss-webpack-plugin').default
const WindiCSS = require('../../dist').default

module.exports = {
  webpack: config => {
    config.plugins.push(new WindiCSS())
    return config
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
}

```

5. Run `yarn build` and see the error

![image](https://user-images.githubusercontent.com/31850793/124764073-2d536e00-df67-11eb-87de-650e3e7aa56a.png)

**Expected behavior**

Build succeeded.

**Comment by rlaphoenix** [comment]
I too am having this problem. Specifically, in my case the area of the code being pointed out is the start of `windicss/plugin/forms`, or at least appears to be.

However, in my case npm run dev (`next dev`) doesn't have any problems, not even a warning. It's only npm build (`next build`) with the problem.

![image](https://user-images.githubusercontent.com/17136956/124877643-2f4b1a80-dfc3-11eb-9dcb-7ff27ddc8d1a.png)

**Comment by ModyQyW** [comment]
`next dev` is also fine to me. Only `next build` having the issue.

I try webpack 4 and it works well.

```js
// const WindiCSS = require('windicss-webpack-plugin').default
const WindiCSS = require('../../dist').default

module.exports = {
  webpack: config => {
    config.plugins.push(new WindiCSS())
    return config
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  webpack5: process.env.NODE_ENV === 'development',
}
```

**Comment by harlan-zw** [comment]
Thanks guys, taking a look

**Comment by harlan-zw** [comment]
@ModyQyW @rlaphoenix 

Thanks for reporting the bug. Looks like something weird going on with webpack 5 and next re-ordering the loader.

Should be fixed in release v1.2.5, can you try that version and let me know how it goes

**Comment by ModyQyW** [comment]
@harlan-zw Works now. Thanks! :D

**Comment by rlaphoenix** [comment]
I would also like to mention that when I change something in my code, e.g. a className, save, and npm dev reloads does whatever it needs to do, `windicss` doesnt get set. As in, no CSS seems to get applied, at all.

**Comment by harlan-zw** [comment]
hey @rlaphoenix 

I have noticed that there is a bug with the regex class matcher, for example given this code

```js
  <div className="{ 'pl-20px **bg-yellow-300 font-white** text-2xl' }">
            Should be Yellow
          </div>
```

Only the bolded classes here will work. You can get around that by adding spaces at the end and start

```js
  <div className="{ '** pl-20px bg-yellow-300 font-white text-2xl  **' }">
            Should be Yellow
          </div>
```
