### ISSUE TITLE
[NextJS] Page WindiCSS being removed on next page build if any change occurred in `next dev`

### ISSUE THREAD

**Issue by rlaphoenix** [windicss/windicss-webpack-plugin#86]
**Describe the bug**
When I change something in a page, be it some JSX, className value, some text, anything, the CSS stops working, and never recovers. It seems to occur whenever ANY sort of page gets built **after an edit is made, prior to the page build**. It doesn't even have to be a user-made page in /pages. It can even be the `build page: /next/dist/pages/_error`.

**To Reproduce**
1. Clone repository https://github.com/windicss/windicss-webpack-plugin
2. Run `npm run dev:nextjs`
3. Edit `example/next/pages/index.jsx` and change the top "Should be Yellow" to "Should be Yellow123". Hit save and see the change appear.
4. Go to any other page (force a 404 if needed, this works too, but do Step 2 to 4 quickly before it prebuilds).
5. Now go back to https://localhost:3000 and see the "Should be Yellow123", notice how it's clearly white BG and black text, default font-family, and the rest of the page is seemingly relatively blank CSS.

**Expected behavior**
The CSS should still have applied like normal.

**Screenshots**
Before:
![Before](https://user-images.githubusercontent.com/17136956/124900414-f027c400-dfd8-11eb-8f7b-f1e633867943.png)

After:
![After](https://user-images.githubusercontent.com/17136956/124900242-c9698d80-dfd8-11eb-8fb5-3de7e791738e.png)

**Additional context**
Even refreshing the page multiple times, going back and forth between pages, etc. won't do anything. Only fix? Stop and restart the `next dev`.

**Comment by harlan-zw** [comment]
Thanks @rlaphoenix, will try get to it tomorrow

**Comment by harlan-zw** [comment]
Hey @rlaphoenix 

I was able to replicate this issue, it was a pretty annoying one to try and fix but I think I may have a 'bandaid' solution. Basically, we invalidate the module with the full source so that HMR's can't trigger broken virtual module states.

Would you mind doing some testing on  1.3.0 to see if you can replicate it or if it causes new problems?

**Comment by rlaphoenix** [comment]
> 
> 
> Hey @rlaphoenix
> 
> I was able to replicate this issue, it was a pretty annoying one to try and fix but I think I may have a 'bandaid' solution. Basically, we invalidate the module with the full source so that HMR's can't trigger broken virtual module states.
> 
> Would you mind doing some testing on 1.3.0 to see if you can replicate it or if it causes new problems?

1.3.0 does seem to fix the problem where it resets the CSS and goes blank, but it doesn't ultimately fix the problem. It doesn't reset the CSS when you follow the reproduction steps, but it does not add any new CSS changes either, when you change/remove/add a className for example.

I think this may not have been spotted since the example code only has one page, and for this to work it seems like again you need to:

A) have the change happen before either any other page builds, or  
B) before the specific page with the change builds (in that case, before the first time you access the page).

I'm not 100% sure which of the two it specifically happens with, or perhaps both.

![image](https://user-images.githubusercontent.com/17136956/125037343-eb701800-e08b-11eb-9f27-50e4b4448f23.png)

This little box is my prime example here. It should be bg-red-400, but instead, it's white. The class name change is there, but the CSS seemingly has no class bg-red-400 in its generated file.

To reproduce this specifically:

1. Follow steps 1-2 on the OG post.
2. Create a new page, e.g. `pages/test.jsx` with a `<div className="bg-blue-400">Test</div>`.
3. `npm run dev` and go to https://localhost:3000 (not /test yet).
4. Change some windicss in `pages/test.jsx`, like the bg-blue-400 to bg-red-400.
5. Now navigate to https://localhost:3000/test and you will see it is in fact no longer bg-blue-400, but it also has bg-red-400 that isn't actually taking place, as it isn't in the generated windicss.

**Comment by rlaphoenix** [comment]
Is there any update on this?

**Comment by harlan-zw** [comment]
Hey @rlaphoenix 

Thanks again for the detailed issue and patience. I dived into the issue to try and find the problem, it seems it was around the invalid hooks in webpack5 reporting null entries.

What it will now do is when it detects these null entries, it will re-scan all your files when generating the virtual module.

Can you try with 1.4.0 and confirm the issue is resolved?

**Comment by rlaphoenix** [comment]
Amazing, it seems to work as expected now. Thank you!
