### ISSUE TITLE
Module not found: Can't resolve 'windi.css'

### ISSUE THREAD

**Issue by 0x219** [windicss/windicss-webpack-plugin#87]
**Describe the bug**
Module not found: Can't resolve 'windi.css'

**To Reproduce**
None
**Expected behavior**
Normal start.

**Screenshots**
![image](https://user-images.githubusercontent.com/50414099/125380765-5049ac00-e3c5-11eb-99c1-7ee0e7ae805d.png)

**Additional context**

version: v1.3.0
os: mac os 11.4

**Comment by 0x219** [comment]
。。。

**Comment by hsuan9522** [comment]
@0x219 Hi, how you solve this problem? I'm not use Next.js, but still has the same issue.

**Comment by 0x219** [comment]
> @0x219 Hi, how you solve this problem? I'm not use Next.js, but still has the same issue.

弃用
