### ISSUE TITLE
Node.js crashed when using windicss and mdx-bundler in Next.js dev mode.

### ISSUE THREAD

**Issue by tmkx** [windicss/windicss-webpack-plugin#93]
**Describe the bug**
Node.js crashed when using `windicss` and `mdx-bundler` in Next.js dev mode.

**To Reproduce**
1. Clone repository https://github.com/tmkx/next-windi
2. Run `pnpm dev`
3. Open `http://localhost:3000/posts/hello-world`

**Behavior**
mdx-bundler + dev/build = ✅
windi + dev/build = ✅
windi + mdx-bundler + build = ✅
windi + mdx-bundler + dev = ❌
![image](https://user-images.githubusercontent.com/13805071/132939735-e9d34f31-337c-408c-b8a4-94412f7a01f2.png)

**Additional context**
[`postcss-windicss`](https://github.com/windicss/postcss-windicss) has the same problem.
Tested in Node v14.17.3.

**Comment by tmkx** [comment]
I have figured out that it's caused by:

1. windicss-webpack-plugin
https://github.com/windicss/windicss-webpack-plugin/blob/d2252189e5c189710a0a4b9dd9eaef6a64b54888/src/plugin.ts#L236

2. @windicss/plugin-utils
https://github.com/windicss/vite-plugin-windicss/blob/71308dbedbf40268ee2d1dd517d0dabcf8652809/packages/config/src/index.ts#L71

3. jiti
https://github.com/unjs/jiti/blob/a7e3eaca580daf54ced23bd3097e2ea2d61ef914/lib/index.js#L13

Remove `require('../dist/v8cache')` and it works.

**Comment by harlan-zw** [comment]
Hey @tmkx 

Thanks for the detailed issue and the debugging! I've taken a look and have been able to replicate the issue and come to the same conclusion on the issue.

It seems that jiti is having a conflict with the mdx-bundler package, maybe something with esbuild.

Jiti is used in the config resolving package, so I've made an issue there for making jiti optional (https://github.com/windicss/vite-plugin-windicss/issues/233) which seems like it would solve the issue. Although you may need to either inline your config or make it plain js.

**Comment by tmkx** [comment]
The root cause is that `jiti` uses `v8-compile-cache`, `require` will be rewritten and make importing esm in cjs context an error.

relevant code:
https://github.com/kentcdodds/mdx-bundler/blob/f6bebc9e4763a91d5ec042ed669c5c726f455d7a/src/index.js#L41-L47

jiti issue and minimum code to replicate:
https://github.com/unjs/jiti/issues/38

We can set the environment variable `DISABLE_V8_COMPILE_CACHE=1` to disable the cache, but it's not a normal way to have to let all users do that.

**Comment by harlan-zw** [comment]
Ah nice one, looks like you're more across this issue than me. Thanks for making the jiti issue.

Do you think this issue would still be helpful https://github.com/windicss/vite-plugin-windicss/issues/233?

Or would a jiti issue fix resolve it

**Comment by tmkx** [comment]
maybe exposing an option to disable v8cache in `jiti` is more suitable 🤔

I've made a pr to fix that: https://github.com/unjs/jiti/pull/39
