### ISSUE TITLE
types: default exports doesn't work in commonjs

### ISSUE THREAD

**Issue by oyzhen** [windicss/windicss-webpack-plugin#99]
**Describe the bug**
types: default exports doesn't work in commonjs.

**Steps**
Enable ts-check in `next.config.js`

```js
// @ts-check
```
Then, ts-check error occurs:

![image](https://user-images.githubusercontent.com/52534412/140250483-848715dc-530b-46ca-8c8f-15b28a693ce4.png)
![image](https://user-images.githubusercontent.com/52534412/140250509-a3da131e-ef07-401d-a7f9-b0c5b7a621f9.png)

**Comment by harlan-zw** [comment]
This one should have been solved to the migration to unbuild, going to close it off. Please re-open if it's still an issue
